spring:
  datasource:
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource

#security:
      ##    user:
      ##      name: lxw
    ##      password: 123456
    ##      roles: -USER